name: sweeteditor
description: "Flutter/Dart FFI wrapper for the SweetEditor native code editor engine."
homepage: https://github.com/FinalScave/OpenSweetEditor
repository: https://github.com/FinalScave/OpenSweetEditor
issue_tracker: https://github.com/FinalScave/OpenSweetEditor/issues
resolution: workspace
version: 1.0.0

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  code_assets: ^1.0.0
  ffi: ^2.1.4
  hooks: ^1.0.0
  logging: ^1.3.0
  native_toolchain_c: ^0.17.4

dev_dependencies:
  ffigen: ^20.1.1
  flutter_lints: ^6.0.0
  test: ^1.28.0
