export const DEFAULT_COMPLETION_DEBOUNCE_CHARACTER_MS = 50;
export const DEFAULT_COMPLETION_DEBOUNCE_INVOKED_MS = 0;
export const DEFAULT_LINE_ANALYZE_CHUNK_BUDGET_MS = 6;

export const DEFAULT_DECORATION_SCROLL_REFRESH_MIN_INTERVAL_MS = 50;
export const DEFAULT_DECORATION_OVERSCAN_VIEWPORT_MULTIPLIER = 0.5;
