import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:sweeteditor/editor_core.dart' as core;
import 'package:sweeteditor/sweeteditor.dart';

import 'demo_completion_provider.dart';
import 'demo_decoration_provider.dart';
import 'demo_file_metadata.dart';

void main() {
  runApp(const SweetEditorDemoApp());
}

class SweetEditorDemoApp extends StatelessWidget {
  const SweetEditorDemoApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'SweetEditor Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(useMaterial3: true, brightness: Brightness.dark),
      home: const EditorDemoPage(),
    );
  }
}

class EditorDemoPage extends StatefulWidget {
  const EditorDemoPage({super.key});

  @override
  State<EditorDemoPage> createState() => _EditorDemoPageState();
}

class _EditorDemoPageState extends State<EditorDemoPage> {
  static const int _styleColor = EditorTheme.styleUserBase;

  static const String _sampleCode = '''
#include <stdio.h>
#include <stdlib.h>

// A simple linked list node
typedef struct Node {
    int data;
    struct Node* next;
} Node;

// TODO: add error handling for edge cases
Node* create_node(int data) {
    Node* node = (Node*)malloc(sizeof(Node));
    if (node == NULL) {
        fprintf(stderr, "Memory allocation failed\\n");
        return NULL;
    }
    node->data = data;
    node->next = NULL;
    return node;
}

void print_list(Node* head) {
    Node* current = head;
    while (current != NULL) {
        printf("%d -> ", current->data);
        current = current->next;
    }
    printf("NULL\\n");
}

// FIXME: potential memory leak if called twice
void free_list(Node* head) {
    Node* current = head;
    while (current != NULL) {
        Node* temp = current;
        current = current->next;
        free(temp);
    }
}

class Color {
    int value = 0xFF5E6778;
    const int highlight = 0xFFE0AF68;
};

int main() {
    Node* head = create_node(1);
    head->next = create_node(2);
    head->next->next = create_node(3);
    head->next->next->next = create_node(4);

    printf("Linked list: ");
    print_list(head);

    free_list(head);
    return 0;
}
''';

  late final SweetEditorController _controller;
  bool _isDarkTheme = true;
  core.WrapMode _wrapMode = core.WrapMode.none;
  String _statusText = 'Ready';
  Timer? _suggestionTimer;

  @override
  void initState() {
    super.initState();
    _controller = SweetEditorController();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      _setupEditor();
    });
  }

  @override
  void dispose() {
    _suggestionTimer?.cancel();
    super.dispose();
  }

  void _setupEditor() {
    final settings = _controller.settings;
    if (settings != null) {
      settings.setFoldArrowMode(core.FoldArrowMode.auto_);
      settings.setCurrentLineRenderMode(core.CurrentLineRenderMode.border);
      settings.setMaxGutterIcons(1);
    }

    _controller.addCompletionProvider(DemoCompletionProvider());
    _controller.addDecorationProvider(
      DemoDecorationProvider((line) => _controller.getLineText(line)),
    );

    _controller.subscribe<TextChangedEvent>(_onTextChanged);
    _controller.subscribe<CursorChangedEvent>(_onCursorChanged);

    _controller.setInlineSuggestionListener(
      _DemoSuggestionListener(
        onAccepted: () => _updateStatus('Accepted suggestion'),
        onDismissed: () => _updateStatus('Dismissed suggestion'),
      ),
    );

    _controller.metadata = const DemoFileMetadata('sample.cpp');
    _controller.loadText(_sampleCode);
    _updateStatus('Loaded: sample.cpp');
  }

  void _onTextChanged(TextChangedEvent e) {
    final rangeStr = e.changeRange != null
        ? '${e.changeRange!.start.line}:${e.changeRange!.start.column}'
              '-${e.changeRange!.end.line}:${e.changeRange!.end.column}'
        : 'null';
    _updateStatus('${e.action.name} $rangeStr');
  }

  void _onCursorChanged(CursorChangedEvent e) {
    _scheduleSuggestionIfAtLineEnd(e);
  }

  void _scheduleSuggestionIfAtLineEnd(CursorChangedEvent event) {
    _suggestionTimer?.cancel();
    _suggestionTimer = null;

    if (_controller.hasSelection) return;

    final line = event.cursorPosition.line;
    final column = event.cursorPosition.column;
    final lineText = _controller.getLineText(line);
    if (lineText.isEmpty ||
        column != lineText.length ||
        lineText.trim().isEmpty) {
      return;
    }

    _suggestionTimer = Timer(const Duration(seconds: 1), () {
      if (_controller.isInlineSuggestionShowing) return;
      const demoText =
          '\nvoid autoGenerated() {\n    std::cout << "hello" << std::endl;\n    return;\n}';
      _controller.showInlineSuggestion(
        InlineSuggestion(line: line, column: column, text: demoText),
      );
    });
  }

  void _toggleTheme() {
    setState(() {
      _isDarkTheme = !_isDarkTheme;
    });
    final theme = _isDarkTheme ? EditorTheme.dark() : EditorTheme.light();
    theme.defineTextStyle(
      _styleColor,
      core.TextStyle(color: _isDarkTheme ? 0xFFB5CEA8 : 0xFF098658),
    );
    _controller.setTheme(theme);
    _updateStatus(_isDarkTheme ? 'Dark theme' : 'Light theme');
  }

  void _cycleWrapMode() {
    final modes = core.WrapMode.values;
    _wrapMode = modes[(_wrapMode.value + 1) % modes.length];
    _controller.settings?.setWrapMode(_wrapMode);
    _updateStatus('WrapMode: ${_wrapMode.name}');
  }

  void _updateStatus(String message) {
    if (mounted) setState(() => _statusText = message);
  }

  @override
  Widget build(BuildContext context) {
    final isDark = _isDarkTheme;
    final bgColor = Color(isDark ? 0xFF1B1E24 : 0xFFFAFBFD);
    final fgColor = Color(isDark ? 0xFFD7DEE9 : 0xFF1F2937);
    final secondaryColor = Color(isDark ? 0xFF5E6778 : 0xFF8A94A6);

    final theme = _isDarkTheme ? EditorTheme.dark() : EditorTheme.light();
    theme.defineTextStyle(
      _styleColor,
      core.TextStyle(color: isDark ? 0xFFB5CEA8 : 0xFF098658),
    );

    return Scaffold(
      backgroundColor: bgColor,
      body: SafeArea(
        child: Column(
          children: [
            _buildToolbar(bgColor, fgColor),
            Expanded(
              child: SweetEditorWidget(
                controller: _controller,
                theme: theme,
                fontFamily:
                    defaultTargetPlatform == TargetPlatform.iOS ||
                        defaultTargetPlatform == TargetPlatform.macOS
                    ? 'Menlo'
                    : 'monospace',
                fontSize: 14,
              ),
            ),
            _buildStatusBar(bgColor, secondaryColor),
          ],
        ),
      ),
    );
  }

  Widget _buildToolbar(Color bgColor, Color fgColor) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 6),
      color: bgColor,
      child: Row(
        children: [
          Expanded(
            child: Text(
              'sample.cpp',
              style: TextStyle(color: fgColor, fontSize: 13),
              overflow: TextOverflow.ellipsis,
            ),
          ),
          _iconButton(Icons.undo, fgColor, () {
            if (_controller.canUndo) {
              _controller.undo();
              _updateStatus('Undo');
            } else {
              _updateStatus('Nothing to undo');
            }
          }),
          _iconButton(Icons.redo, fgColor, () {
            if (_controller.canRedo) {
              _controller.redo();
              _updateStatus('Redo');
            } else {
              _updateStatus('Nothing to redo');
            }
          }),
          _iconButton(Icons.brightness_6, fgColor, _toggleTheme),
          _iconButton(Icons.wrap_text, fgColor, _cycleWrapMode),
        ],
      ),
    );
  }

  Widget _iconButton(IconData icon, Color color, VoidCallback onPressed) {
    return IconButton(
      icon: Icon(icon, size: 20, color: color),
      onPressed: onPressed,
      padding: const EdgeInsets.all(6),
      constraints: const BoxConstraints(minWidth: 36, minHeight: 36),
    );
  }

  Widget _buildStatusBar(Color bgColor, Color textColor) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 5),
      color: bgColor,
      child: Text(
        _statusText,
        style: TextStyle(color: textColor, fontSize: 11),
        maxLines: 1,
        overflow: TextOverflow.ellipsis,
      ),
    );
  }
}

class _DemoSuggestionListener implements InlineSuggestionListener {
  _DemoSuggestionListener({
    required this.onAccepted,
    required this.onDismissed,
  });

  final VoidCallback onAccepted;
  final VoidCallback onDismissed;

  @override
  void onSuggestionAccepted(InlineSuggestion suggestion) => onAccepted();

  @override
  void onSuggestionDismissed(InlineSuggestion suggestion) => onDismissed();
}
